### ISSUE TITLE
Conflicting gradient ids after merge?

### ISSUE THREAD

**Issue by Jakobud** [w0rm/gulp-svgstore#38] opened 2015-07-10 03:21 UTC
I have two SVGs. Each one had `linearGradient`s defined. The first one has it like this:

```
<linearGradient id="SVGID_3_" gradientUnits .... etc
```
and the second one has a linear gradient with the same id:

```
<linearGradient id="SVGID_3_" x1="29.6744" y1="50.....
```

So now, after `svgstore` combined my SVGs, I have two different linear gradients with the same IDs. That means there are conflicts and the gradients get used on the wrong svg sprites.

How do I avoid this? I'm working with SVGs that are generated by Adobe Illustrator. It pretty much chooses it's own naming convention for the gradient ids for each separate SVG. It's no wonder they aren't unique to each other.

Short of manually changing the IDs, what is the best approach to solving this? Surely I'm not the first person to come across this issue right?

**Comment by Jakobud** [comment] 2015-07-10 03:25
Grunt Svgstore issues seem to suggest that gradient id's are prepended with a file hash, making them unique to that file:

https://github.com/FWeinb/grunt-svgstore/issues/78

But I don't see this functionality in gulp svgstore unless I'm missing something obvious...

**Comment by w0rm** [comment] 2015-07-10 05:25
@Jakobud this is a known issue, closing it as a duplicate of #33.

**Closed by w0rm** 2015-07-10 05:25 UTC
