### ISSUE TITLE
Gradients not rendering

### ISSUE THREAD

**Issue by rctneil** [w0rm/gulp-svgstore#56] opened 2015-10-31 15:56 UTC
Hey,

Been testing out gulp-svgstore for my new site. I have got it working on quite a few SVG's and it's great.

However, any svg's that contain gradients do not render them. On;y the solid fill areas show up. I have read everything I can find to locate a solution but can't seem to get anything to work. I tried moving a linearGradient blog out of the <symbol> and this allows it to display in Firefox but still nothing in Chrome.

I also have a lot of SVG's and quite a few have a lot of gradients so it's a big issue for me here. Is there a solution to this and if so, is there an automated way that can be done as part of the gulp workflow and svgstore task?

**Comment by w0rm** [comment] 2015-10-31 15:59
@rctneil hi, I think this issue is the same as https://github.com/w0rm/gulp-svgstore/issues/55

**Comment by rctneil** [comment] 2015-10-31 16:00
I did read that but it doesn't make sense to me. Also, I am using externally referenced SVG so unsure if that makes a difference.

**Comment by w0rm** [comment] 2015-10-31 16:02
@rctneil can you provide a source of an example svg that is broken when used from combined file?

**Comment by rctneil** [comment] 2015-10-31 16:05
@w0rm Ok, This SVG has a gradient and the gradient part doesn't show in Chrome. If I move the gradient out of the symbol then the gradient parts shows in Firefox but still not in Chrome:

https://gist.github.com/rctneil/a69743e09be0d44ac309?short_path=f99ea3c

**Comment by w0rm** [comment] 2015-10-31 16:48
@rctneil I was able to reproduce the issue, wrapping gradient inside `defs` fixes the issue in Firefox, but not in Chrome. 

I'm really not sure why its not working.

**Comment by rctneil** [comment] 2015-10-31 18:28
@w0rm It's odd. How are other people using this plugin solving the issue? Surely they must be encountering it?

This is happening for every SVG that I have with some form of gradient.

**Comment by w0rm** [comment] 2015-10-31 19:17
Maybe they inline combined svg into the page. I'm not using svgstore for complex svgs, but rather for monochrome icons.

**Comment by w0rm** [comment] 2015-10-31 19:40
I'd like to see this issue tracked down to an explanation of why its broken or maybe even a Chrome bug report.

**Comment by rctneil** [comment] 2015-10-31 19:41
@w0rm I've just reverted to an inline option and all the gradients display. Weird.

**Comment by w0rm** [comment] 2015-10-31 19:46
@rctneil I was able to find [this question on stackoverflow](http://stackoverflow.com/questions/27752494/why-cant-i-reference-an-svg-linear-gradient-defined-in-an-external-file-paint) with a links to chromium and webkit bugs.

**Comment by daviddarnes** [comment] 2015-11-11 12:50
@w0rm I don't think it's quite the same as the question refers to an external file. I've just used svgstore on [this project](http://daviddarnes.github.io/mac-cursors/) and the gradients are missing, all of the SVGs are inline. The first icon in the grid [should be shown like this](https://github.com/daviddarnes/mac-cursors/blob/master/svg/busybutclickable.svg).

**Comment by w0rm** [comment] 2015-11-16 10:41
@daviddarnes yes, your issue is different from this one. I'm closing this one because thats how Chrome works, if you use symbols from external svg and they link to gradients or other objects from within that external svg — then external objects don't render.

Regarding two gradients with the same id, svgstore simply merges all svgs together, you need to ensure this yourself that ids do not clash. This can be done with gulp-svgmin, check the very first example from the readme https://github.com/w0rm/gulp-svgstore#usage

**Closed by w0rm** 2015-11-16 10:41 UTC

**Comment by daviddarnes** [comment] 2015-11-16 11:01
@w0rm thanks for the reply. Upon further investigation it appears that Sketch is quite poor when it comes to naming and managing gradients, it merely numbers them. So when combining SVGs with gradients it will almost always clash. At some point I should probably use cheerio in the gulp task to name the gradients.

Sorry for pointing the blame in the wrong direction. Thanks for open sourcing!

**Comment by w0rm** [comment] 2015-11-16 11:16
@daviddarned why isn't the proposed solution working for you? It ensures unique ids automatically and also minifies svgs

**Comment by daviddarnes** [comment] 2015-11-16 12:23
@w0rm I wasn't using svgmin at the time, thought it was causing another issue. I changed the IDs myself and everything works fine. Despite svgmin solving the gradient issue, it would still be nice if Sketch didn't just number gradients like that.
